"""cascade on deletion

Revision ID: 7d1e5ca10db4
Revises: 2a42cfa713b1
Create Date: 2025-08-25 00:45:12.341553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1e5ca10db4'
down_revision: Union[str, Sequence[str], None] = '2a42cfa713b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tables = ['note', 'quote', 'review']
    for table in tables:
        with op.batch_alter_table(table, recreate="always") as batch_op:
            batch_op.drop_constraint("table", type_="foreignkey")
            batch_op.create_foreign_key(
                None,
                table,
                "book_club_reader"
                ["book_club_reader_id"],
                ["id"],
                ondelete="CASCADE",
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    tables = ['note', 'quote', 'review']
    for table in tables:
        with op.batch_alter_table(table, recreate="always") as batch_op:
            batch_op.drop_constraint("table", type_="foreignkey")
            batch_op.create_foreign_key(
                None,
                table,
                "book_club_reader"
                ["book_club_reader_id"],
                ["id"],
            )
    # ### end Alembic commands ###
