"""add book fields

Revision ID: b22426f9e117
Revises: 0fb2db7d5071
Create Date: 2025-08-24 21:15:16.989380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22426f9e117'
down_revision: Union[str, Sequence[str], None] = '0fb2db7d5071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('rating', sa.Float(), nullable=True))
    op.add_column('book', sa.Column('pages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'pages')
    op.drop_column('book', 'rating')
    op.drop_column('book', 'year')
    # ### end Alembic commands ###
